POST https://cowork-api-spmiw.run.goorm.io/api/members
Content-Type: application/json

{
  "name": "July",
  "team": "Secure",
  "birthday": "2004/07/04",
  "admissionDate": "2012/07/19"
}

###
PUT https://cowork-api-spmiw.run.goorm.io/api/members/7
Content-Type: application/json

{
  "name": "June",
  "admissionDate": "2012/05/19"
}

###
DELETE http://localhost:3030/api/members/8